GET localhost:8080/account
Content-Type: application/json

###

GET localhost:8080/account/1002
Content-Type: application/json

###

POST localhost:8080/account
Content-Type: application/json

{
  "address": "SmallBoobStreet 1",
  "email": "Batman@iAmBatman.com",
  "id": 1004,
  "name": "Batman manbat",
  "phone": "+43 690 14166621"
}

###

GET localhost:8080/debtor
Content-Type: application/json

###

GET localhost:8080/debtor/3
Content-Type: application/json

###

POST localhost:8080/debtor
Content-Type: application/json

{
  "account": {
    "address": "superstreet 1",
    "email": "super@man.com",
    "id": 1006,
    "name": "Super Man",
    "phone": "+43 664 0487625"
  },
  "id": 7,
  "name": "Florian Klausner"
}

###

GET localhost:8080/entry
Content-Type: application/json

###

GET localhost:8080/entry/3
Content-Type: application/json

###

POST localhost:8080/entry
Content-Type: application/json

{
  "amount": 69.79,
  "date": "2022-09-13T16:49:29.148846",
  "debtor": {
    "account": {
      "address": "WitzigStraße 2",
      "email": "witzig@gmail.com",
      "id": 1009,
      "name": "Sandra Miningsdorfer",
      "phone": "+43 664 23432423"
    },
    "id": 3,
    "name": "Sebastian Scholl"
  },
  "edited": false,
  "id": 7,
  "reason": "Cool zu cool Swag"
}

###

